# Generated by Django 3.0.3 on 2020-03-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_2', '0003_auto_20200209_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoolCompare',
        ),
        migrations.RenameField(
            model_name='resultpoolservice',
            old_name='pool',
            new_name='flag',
        ),
        migrations.RenameField(
            model_name='resultpoolservice',
            old_name='ticket',
            new_name='r_ticket',
        ),
    ]
