# Generated by Django 3.0.3 on 2020-03-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool_2', '0005_auto_20200301_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('r_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_2.ResultPoolService')),
            ],
        ),
    ]
